#* prod
services:
  mirero-ojt:
    build:
      context: . # 이미지 빌드할 경로
      dockerfile: Dockerfile-prod # 빌드 시 사용할 도커파일
    ports:
      - "80:80"
     # 컨테이너 상태 확인
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
