#* dev
services:
  mirero-ojt:
    build:
      context: .  # 이미지 빌드할 경로
      dockerfile: Dockerfile-dev # 빌드 시 사용할 도커파일
    ports:
      - "3000:3000"
    # 코드 변경 시 자동 반영
    volumes:
      - .:/app:cached
      # npm install로 생성된 node_modules는 컨테이너 내부 꺼로 사용
      - /app/node_modules   
# 파일 변경 감지 안정화   
environment:
  - CHOKIDAR_USEPOLLING=true
